### ISSUE TITLE
Update documentation to mention new supported python versions

### ISSUE THREAD

**Issue by sanjayankur31** [robgolding/tasklib#66]
The docs say it supports 3.3, but it seems to build and run fine on 3.7 here on Fedora 30/31. So, could we update the docs and `setup.py` please to say so?

**Comment by robgolding** [comment]
Sure, we should update the test matrix to ensure compatibility with newer versions (and perhaps drop some older ones).

**Comment by tbabej** [comment]
Fixed by bd70754.
